### ISSUE TITLE
Question: Where are views stored?

### ISSUE THREAD

**Issue by uPagge** [philip306/countapi#3]
It is logical that the counters are stored somewhere, could you tell me how to mount the folder in docker-compose in order to access this data from the machine.

It's just that after restarting the system, the views fly off ((

Apologies if my question is stupid, I just didn't work with redis.

**Comment by uPagge** [comment]
I think I figured it out, but I would be glad if you confirmed

```
redis:
        image: redis
        entrypoint: redis-server --appendonly yes
        volumes:
            - ./data:/data
```
